version: '3.3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sunatlem_event
        ports: 
            - 8080:8000
        restart: on-failure
        volumes: 
            - ./:/code
        environment:
            - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
            - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
            - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
        depends_on:
            - postgres
        networks:
            - sunatlem

    postgres:
        image: postgres:14-alpine
        container_name: postgres_db
        ports: 
            - 5433:5432
        volumes: 
            - database_postgres:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        networks:
            - sunatlem
        
volumes: 
    database_postgres:

networks:
    sunatlem:
        driver: bridge
