# Generated by Django 4.1.2 on 2022-10-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craftsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('profile_img', models.ImageField(upload_to='craftsman')),
            ],
        ),
        migrations.CreateModel(
            name='CrafstmanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftsman.craftsman')),
            ],
        ),
    ]
