# Generated by Django 4.1.2 on 2022-10-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0004_craftsman_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsmanservice',
            name='craftsman',
        ),
    ]
