# Generated by Django 4.1.2 on 2022-10-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0002_craftsman_crafstmanservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrafstmanService',
            new_name='CraftsmanService',
        ),
    ]
