# Generated by Django 4.1.2 on 2022-10-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0005_remove_craftsmanservice_craftsman'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='services',
            field=models.ManyToManyField(to='craftsman.craftsmanservice'),
        ),
    ]
